name : cicd-workflow
on :
- push

jobs:
  cicd_assignment:
    name: CICD Assignment
    runs-on : ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        ref: ${{github.ref_name}}
        token: ${{github.token}}
    - name: Run vulnerability Scanner
      id: vul_check
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-results.txt'
        exit-code: '1'
        severity: 'CRITICAL'
    - name: failure slack notification
      id: failure_slack_notification
      if: failure()
      run: echo "failure_slack_notification"
    - name: upload report to slack
      id: upload_to_slack
      if: failure()
      run: cat trivy-results.txt
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: success()
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      if: success()
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: preethivenkat5/cicd_docker_project
    - name: cosign
      id: cosign
      if: success()
      run: echo "cosign"
    - name: success slack notification
      id: success_slack_notification
      if: success()
      run: echo "success_slack_notification"