name : cicd-workflow
on :
- push
jobs:
  cicd_assignment:
    name: CICD Assignment
    runs-on : ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        ref: ${{github.ref_name}}
        token: ${{github.token}}