name : cicd-workflow
on :
- push

jobs:
  cicd_assignment:
    name: CICD Assignment
    runs-on : ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        ref: ${{github.ref_name}}
        token: ${{github.token}}
    - name: Run vulnerability Scanner
      id: vul_check
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'table'
        output: 'trivy-results.txt'
        exit-code: '1'
        severity: 'HIGH'
    - name: failure slack notification
      id: failure_slack_notification
      run: echo "failure_slack_notification"
    - name: upload report to slack
      id: upload_to_slack
      run: cat trivy-results.txt